In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
arr=np.array([1,2,3,4,5],dtype="float")
arr

array([1., 2., 3., 4., 5.])

In [4]:
ar1=np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

### pandas
- it is a important module in data science libraries
- stands for pannel data
- data Structures
    -series
    -dataframes
- with this we can do the data analysis,manipulations,cleaning
- data analysation
     - statistics of the data
     - volume of the data
 - data manipulation
     - changing data from one form to another
     - merging and concatenation
 - data cleaning
     - deleting unwanted data
     - deleting null values and Nan values..etc
     

In [9]:
import pandas as pd

In [10]:
pd.__version__

'1.2.4'

In [12]:
# we can create the pandas series with list,string,tuple and also dictionaries

In [14]:
#print(dir(pd))

In [15]:
a=pd.Series("i am from VR")
a

0    i am from VR
dtype: object

In [17]:
b=input()
c=pd.Series(b.split(" "))
c

i am from VR


0       i
1      am
2    from
3      VR
dtype: object

In [18]:
t=(4,5,6,7,8)
t1=pd.Series(t)
t1

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [19]:
l1=[2,3,4,5,6]
l2=pd.Series(l1)
l2

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [20]:
d={1:2,2:3,3:4,4:5}
d1=pd.Series(d)
d1

1    2
2    3
3    4
4    5
dtype: int64

In [22]:
a=np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
d=pd.Series(a)
d

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
dtype: int32

In [26]:
d=pd.Series(range(20,26))
d

0    20
1    21
2    22
3    23
4    24
5    25
dtype: int64

In [27]:
dic={"list":[1,2,3],"tuple":(1,2,3),"string":"hii","integer":4}
dic

{'list': [1, 2, 3], 'tuple': (1, 2, 3), 'string': 'hii', 'integer': 4}

In [28]:
d=pd.Series(dic)
d

list       [1, 2, 3]
tuple      (1, 2, 3)
string           hii
integer            4
dtype: object

In [30]:
d.index

Index(['list', 'tuple', 'string', 'integer'], dtype='object')

In [34]:
arr=np.arange(10,50,5)
arr1=pd.Series(arr)
arr1

0    10
1    15
2    20
3    25
4    30
5    35
6    40
7    45
dtype: int32

In [35]:
arr1[0]

10

In [36]:
len(arr1)

8

In [37]:
arr1[len(arr)-1]

45

In [38]:
arr1[0:2]

0    10
1    15
dtype: int32

In [39]:
arr1.index

RangeIndex(start=0, stop=8, step=1)

In [40]:
arr1.index=[223,122,122,3344,2334,123,422,455]
arr1

223     10
122     15
122     20
3344    25
2334    30
123     35
422     40
455     45
dtype: int32

In [42]:
li=["hi","hello","good","hope"]
pd.Series(li,index=(1,2,3,4))

1       hi
2    hello
3     good
4     hope
dtype: object

In [44]:
li=["hi","hello","good","hope"]
ind=[i for i in range(15,19)] #list comprehension
pd.Series(li,index=ind)

15       hi
16    hello
17     good
18     hope
dtype: object

In [45]:
d

list       [1, 2, 3]
tuple      (1, 2, 3)
string           hii
integer            4
dtype: object

In [46]:
dic

{'list': [1, 2, 3], 'tuple': (1, 2, 3), 'string': 'hii', 'integer': 4}

In [48]:
dict2=pd.Series(dic,index=ind)
dict2

15    NaN
16    NaN
17    NaN
18    NaN
dtype: object

In [49]:
dict2.index

Int64Index([15, 16, 17, 18], dtype='int64')

### Data Frames
   - data is in 2nd format

In [50]:
import pandas as pd
import numpy as np
pd.DataFrame(dic)

list  tuple string  integer
0     1      1    hii        4
1     2      2    hii        4
2     3      3    hii        4

In [51]:
data={56:"fiftysix","float":10.23,"prgm":"workshop","name":"DA"}
data

{56: 'fiftysix', 'float': 10.23, 'prgm': 'workshop', 'name': 'DA'}

In [53]:
pd.DataFrame(data,index="i am in Vr".split(" "))

56  float      prgm name
i   fiftysix  10.23  workshop   DA
am  fiftysix  10.23  workshop   DA
in  fiftysix  10.23  workshop   DA
Vr  fiftysix  10.23  workshop   DA

In [54]:
df1=pd.DataFrame(dic)
df2=pd.DataFrame(data,index="i am in Vr".split(" "))

In [56]:
pd.concat([df1,df2])

list  tuple string  integer        56  float      prgm name
0    1.0    1.0    hii      4.0       NaN    NaN       NaN  NaN
1    2.0    2.0    hii      4.0       NaN    NaN       NaN  NaN
2    3.0    3.0    hii      4.0       NaN    NaN       NaN  NaN
i    NaN    NaN    NaN      NaN  fiftysix  10.23  workshop   DA
am   NaN    NaN    NaN      NaN  fiftysix  10.23  workshop   DA
in   NaN    NaN    NaN      NaN  fiftysix  10.23  workshop   DA
Vr   NaN    NaN    NaN      NaN  fiftysix  10.23  workshop   DA

In [58]:
dict3={"first":[1,2,3,4],"second":[5,6,7,8],"third":(45,56,78,79)}
dict3

{'first': [1, 2, 3, 4], 'second': [5, 6, 7, 8], 'third': (45, 56, 78, 79)}

In [59]:
df3=pd.DataFrame(dict3,index=[2001,2002,2003,2004])
df3

first  second  third
2001      1       5     45
2002      2       6     56
2003      3       7     78
2004      4       8     79

In [61]:
df4=pd.DataFrame({'fourth': [10, 20, 30, 40], 
                  'fifth': [50, 60, 70, 80], 
                  'sixth': (450, 560, 780, 790)},
                 index=[2008,2002,2003,2007])
df4

fourth  fifth  sixth
2008      10     50    450
2002      20     60    560
2003      30     70    780
2007      40     80    790

In [62]:
df3.join(df4)

first  second  third  fourth  fifth  sixth
2001      1       5     45     NaN    NaN    NaN
2002      2       6     56    20.0   60.0  560.0
2003      3       7     78    30.0   70.0  780.0
2004      4       8     79     NaN    NaN    NaN

In [63]:
df4.join(df3)

fourth  fifth  sixth  first  second  third
2008      10     50    450    NaN     NaN    NaN
2002      20     60    560    2.0     6.0   56.0
2003      30     70    780    3.0     7.0   78.0
2007      40     80    790    NaN     NaN    NaN

In [69]:
df5=pd.DataFrame({"a":[78,89,56,23],
                  "b":(65,80,34,45),
                  "c":[67,89,45,23]},index="these are integer values".split())
df5

a   b   c
these    78  65  67
are      89  80  89
integer  56  34  45
values   23  45  23

In [78]:
df6=pd.DataFrame({"a":[78,89,56,23],
                  "b":(65,80,344,45),
                  "c":[67,89,45,23]},index="these are integer values".split())
df6

a    b   c
these    78   65  67
are      89   80  89
integer  56  344  45
values   23   45  23

In [79]:
df5.merge(df6)

a   b   c
0  78  65  67
1  89  80  89
2  23  45  23

In [80]:
df6.merge(df5)

a   b   c
0  78  65  67
1  89  80  89
2  23  45  23

In [81]:
df6.merge(df5,on="a")

a  b_x  c_x  b_y  c_y
0  78   65   67   65   67
1  89   80   89   80   89
2  56  344   45   34   45
3  23   45   23   45   23

In [82]:
new=df5.merge(df6)
new.columns=["ab","ba","cb"]
new

ab  ba  cb
0  78  65  67
1  89  80  89
2  23  45  23

In [84]:
new=df5.merge(df6)
new.columns=["ab","ba","cb"]
new.index=(20,30,40)
new

ab  ba  cb
20  78  65  67
30  89  80  89
40  23  45  23

In [85]:
dt=pd.date_range('2022-01-01','2022-01-15')
dt

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15'],
              dtype='datetime64[ns]', freq='D')

In [86]:
dt=pd.date_range('2022-01-01','2022-01-15',periods=6)
dt

DatetimeIndex(['2022-01-01 00:00:00', '2022-01-03 19:12:00',
               '2022-01-06 14:24:00', '2022-01-09 09:36:00',
               '2022-01-12 04:48:00', '2022-01-15 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [87]:
dt=pd.date_range('2022-01-01','2022-01-15',periods=6)
pd.Series(dt)

0   2022-01-01 00:00:00
1   2022-01-03 19:12:00
2   2022-01-06 14:24:00
3   2022-01-09 09:36:00
4   2022-01-12 04:48:00
5   2022-01-15 00:00:00
dtype: datetime64[ns]

In [92]:
temp=[23,45,67,88,12,90]
dt1=pd.Series(temp,index=dt)

In [94]:
dt1["2022-01-06"]

2022-01-06 14:24:00    67
dtype: int64

### working with .csv files
    - reading .csv file with "read_csv()" method
    - syntax:- pd.read_csv("file location")

In [95]:
# reading data
data=pd.read_csv("marks.csv")
data

Roll Name  Maths  Discrete  OS    CO    DS
0    A1    X     60        70  30  70.0  90.0
1    A2    Y     90        45  67  73.0  50.0
2    A1    G     60        70  30   NaN  90.0
3    A2    H     40        60  73  50.0   NaN
4    B1    I     50        70  90  90.0   NaN
5    B2    J     63        45  67  56.0  50.0
6    C1    K     67        70  30  75.0  40.0
7    C2    L     91        45  67  72.0  50.0
8    D1    M     40        70  50   NaN  90.0
9    D2    N      5        67  65  50.0   NaN
10   E1    X     50        70  30  80.0  90.0
11   E2    Y     60        45  77  73.0  40.0

In [96]:
#sample
data.sample()

Roll Name  Maths  Discrete  OS  CO    DS
8   D1    M     40        70  50 NaN  90.0

In [97]:
#sample
data.sample(2)

Roll Name  Maths  Discrete  OS    CO    DS
8   D1    M     40        70  50   NaN  90.0
4   B1    I     50        70  90  90.0   NaN

In [98]:
data.head(2)     

Roll Name  Maths  Discrete  OS    CO    DS
0   A1    X     60        70  30  70.0  90.0
1   A2    Y     90        45  67  73.0  50.0

In [99]:
data.tail(3)

Roll Name  Maths  Discrete  OS    CO    DS
9    D2    N      5        67  65  50.0   NaN
10   E1    X     50        70  30  80.0  90.0
11   E2    Y     60        45  77  73.0  40.0

In [101]:
data.head(1)

Roll Name  Maths  Discrete  OS    CO    DS
0   A1    X     60        70  30  70.0  90.0

In [102]:
data["Roll"]# accesing single col data

0     A1
1     A2
2     A1
3     A2
4     B1
5     B2
6     C1
7     C2
8     D1
9     D2
10    E1
11    E2
Name: Roll, dtype: object

In [107]:
data[["Roll","Name","Maths"]]
# accesing multiple col values

Roll Name  Maths
0    A1    X     60
1    A2    Y     90
2    A1    G     60
3    A2    H     40
4    B1    I     50
5    B2    J     63
6    C1    K     67
7    C2    L     91
8    D1    M     40
9    D2    N      5
10   E1    X     50
11   E2    Y     60

In [109]:
data.columns

Index(['Roll', 'Name', 'Maths', 'Discrete', 'OS', 'CO', 'DS'], dtype='object')

In [110]:
data.index

RangeIndex(start=0, stop=12, step=1)

In [113]:
data.dtypes

Roll         object
Name         object
Maths         int64
Discrete      int64
OS            int64
CO          float64
DS          float64
dtype: object

In [118]:
data.info #text info liikei printing

<bound method DataFrame.info of    Roll Name  Maths  Discrete  OS    CO    DS
0    A1    X     60        70  30  70.0  90.0
1    A2    Y     90        45  67  73.0  50.0
2    A1    G     60        70  30   NaN  90.0
3    A2    H     40        60  73  50.0   NaN
4    B1    I     50        70  90  90.0   NaN
5    B2    J     63        45  67  56.0  50.0
6    C1    K     67        70  30  75.0  40.0
7    C2    L     91        45  67  72.0  50.0
8    D1    M     40        70  50   NaN  90.0
9    D2    N      5        67  65  50.0   NaN
10   E1    X     50        70  30  80.0  90.0
11   E2    Y     60        45  77  73.0  40.0>

In [116]:
data.describe()

Maths   Discrete         OS         CO         DS
count  12.000000  12.000000  12.000000  10.000000   9.000000
mean   56.333333  60.583333  56.333333  68.900000  65.555556
std    22.928083  11.851032  21.465970  13.042239  23.511227
min     5.000000  45.000000  30.000000  50.000000  40.000000
25%    47.500000  45.000000  30.000000  59.500000  50.000000
50%    60.000000  68.500000  66.000000  72.500000  50.000000
75%    64.000000  70.000000  68.500000  74.500000  90.000000
max    91.000000  70.000000  90.000000  90.000000  90.000000

In [125]:
data.Maths.value_counts() #to get frequency of values of a particular col

60    3
50    2
40    2
67    1
5     1
90    1
91    1
63    1
Name: Maths, dtype: int64

In [127]:
data["Maths"].value_counts() #to get frequency of values of a particular col

60    3
50    2
40    2
67    1
5     1
90    1
91    1
63    1
Name: Maths, dtype: int64

In [128]:
data.shape

(12, 7)

In [129]:
data.sort_values("Roll")

Roll Name  Maths  Discrete  OS    CO    DS
0    A1    X     60        70  30  70.0  90.0
2    A1    G     60        70  30   NaN  90.0
1    A2    Y     90        45  67  73.0  50.0
3    A2    H     40        60  73  50.0   NaN
4    B1    I     50        70  90  90.0   NaN
5    B2    J     63        45  67  56.0  50.0
6    C1    K     67        70  30  75.0  40.0
7    C2    L     91        45  67  72.0  50.0
8    D1    M     40        70  50   NaN  90.0
9    D2    N      5        67  65  50.0   NaN
10   E1    X     50        70  30  80.0  90.0
11   E2    Y     60        45  77  73.0  40.0

In [130]:
data.sort_values("Name")

Roll Name  Maths  Discrete  OS    CO    DS
2    A1    G     60        70  30   NaN  90.0
3    A2    H     40        60  73  50.0   NaN
4    B1    I     50        70  90  90.0   NaN
5    B2    J     63        45  67  56.0  50.0
6    C1    K     67        70  30  75.0  40.0
7    C2    L     91        45  67  72.0  50.0
8    D1    M     40        70  50   NaN  90.0
9    D2    N      5        67  65  50.0   NaN
0    A1    X     60        70  30  70.0  90.0
10   E1    X     50        70  30  80.0  90.0
1    A2    Y     90        45  67  73.0  50.0
11   E2    Y     60        45  77  73.0  40.0

In [131]:
data.sort_values("Roll",ascending=False)

Roll Name  Maths  Discrete  OS    CO    DS
11   E2    Y     60        45  77  73.0  40.0
10   E1    X     50        70  30  80.0  90.0
9    D2    N      5        67  65  50.0   NaN
8    D1    M     40        70  50   NaN  90.0
7    C2    L     91        45  67  72.0  50.0
6    C1    K     67        70  30  75.0  40.0
5    B2    J     63        45  67  56.0  50.0
4    B1    I     50        70  90  90.0   NaN
1    A2    Y     90        45  67  73.0  50.0
3    A2    H     40        60  73  50.0   NaN
0    A1    X     60        70  30  70.0  90.0
2    A1    G     60        70  30   NaN  90.0

In [134]:
data["Total"]=100# adding another col
data

Roll Name  Maths  Discrete  OS    CO    DS  Total
0    A1    X     60        70  30  70.0  90.0    100
1    A2    Y     90        45  67  73.0  50.0    100
2    A1    G     60        70  30   NaN  90.0    100
3    A2    H     40        60  73  50.0   NaN    100
4    B1    I     50        70  90  90.0   NaN    100
5    B2    J     63        45  67  56.0  50.0    100
6    C1    K     67        70  30  75.0  40.0    100
7    C2    L     91        45  67  72.0  50.0    100
8    D1    M     40        70  50   NaN  90.0    100
9    D2    N      5        67  65  50.0   NaN    100
10   E1    X     50        70  30  80.0  90.0    100
11   E2    Y     60        45  77  73.0  40.0    100

In [135]:
data.Maths.sum()

676

In [136]:
data.OS.sum()

676

In [137]:
data.CO.sum()

689.0

In [138]:
data.isnull()

Roll   Name  Maths  Discrete     OS     CO     DS  Total
0   False  False  False     False  False  False  False  False
1   False  False  False     False  False  False  False  False
2   False  False  False     False  False   True  False  False
3   False  False  False     False  False  False   True  False
4   False  False  False     False  False  False   True  False
5   False  False  False     False  False  False  False  False
6   False  False  False     False  False  False  False  False
7   False  False  False     False  False  False  False  False
8   False  False  False     False  False   True  False  False
9   False  False  False     False  False  False   True  False
10  False  False  False     False  False  False  False  False
11  False  False  False     False  False  False  False  False

In [139]:
data.isna()

Roll   Name  Maths  Discrete     OS     CO     DS  Total
0   False  False  False     False  False  False  False  False
1   False  False  False     False  False  False  False  False
2   False  False  False     False  False   True  False  False
3   False  False  False     False  False  False   True  False
4   False  False  False     False  False  False   True  False
5   False  False  False     False  False  False  False  False
6   False  False  False     False  False  False  False  False
7   False  False  False     False  False  False  False  False
8   False  False  False     False  False   True  False  False
9   False  False  False     False  False  False   True  False
10  False  False  False     False  False  False  False  False
11  False  False  False     False  False  False  False  False

In [140]:
data.isnull().sum()

Roll        0
Name        0
Maths       0
Discrete    0
OS          0
CO          2
DS          3
Total       0
dtype: int64

In [141]:
data.nunique()

Roll        10
Name        10
Maths        8
Discrete     4
OS           7
CO           8
DS           3
Total        1
dtype: int64

In [142]:
clean=data.dropna()
clean

Roll Name  Maths  Discrete  OS    CO    DS  Total
0    A1    X     60        70  30  70.0  90.0    100
1    A2    Y     90        45  67  73.0  50.0    100
5    B2    J     63        45  67  56.0  50.0    100
6    C1    K     67        70  30  75.0  40.0    100
7    C2    L     91        45  67  72.0  50.0    100
10   E1    X     50        70  30  80.0  90.0    100
11   E2    Y     60        45  77  73.0  40.0    100

In [143]:
data

Roll Name  Maths  Discrete  OS    CO    DS  Total
0    A1    X     60        70  30  70.0  90.0    100
1    A2    Y     90        45  67  73.0  50.0    100
2    A1    G     60        70  30   NaN  90.0    100
3    A2    H     40        60  73  50.0   NaN    100
4    B1    I     50        70  90  90.0   NaN    100
5    B2    J     63        45  67  56.0  50.0    100
6    C1    K     67        70  30  75.0  40.0    100
7    C2    L     91        45  67  72.0  50.0    100
8    D1    M     40        70  50   NaN  90.0    100
9    D2    N      5        67  65  50.0   NaN    100
10   E1    X     50        70  30  80.0  90.0    100
11   E2    Y     60        45  77  73.0  40.0    100