n=list(map(str,input().split()))
sum=0
print(n)
for i in n:
    s=len(i)//2
    print(i[s])
    sum+=int(i[s])
print(sum)
    

## Data Analysis
- Any useful information is called data
- Types of data in devices
    - .txt,.img,.ppt,.mp3,.excel,.doc etc
- Types of data in realtime
    1. Quantitative data
    - Represents the size/volume of data
    -Discrete and continous
    - Discrete Data is constant/fixed
    Ex: Numbers in a dice,color,nationality etc
    - Continuos data means the value/data is continous
    Ex: time,height,weight
    2. Qualitative Data
         - Data is analysed and categorised
          - Ex: DATA SUBMISSION IN FEEDBACK FORM
- Data in statistics
    - Nominal,ordinal,interval and ratio
     - Nominal means data is categorised on the basis of names
         - Ex: color,Nationality,Gender
        - Ordinal means data is categorised upon the orer o vlue
            - Ex: Feedback form
        - Interval means a range of intervak values
            - Ex: time interval in clock
      - ratio means data is 

In [1]:
## numpy
import numpy as np
dir(np)


['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [2]:
np.__version__

'1.20.1'

In [3]:
# numpy means numerical python
# which is used to deal with arrays and scientific computation
# array(): method to create array
# numpy.array([iterable])


In [4]:
np.array([1,2,3,4,5,6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
np.array([1,2,3,4,5,6,7,8],dtype="float") 

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [6]:
np.array([1,2,3,4,5,6,7,8],dtype="int") 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.array([1,2,3,4,5,6,7,8],dtype="str") 

array(['1', '2', '3', '4', '5', '6', '7', '8'], dtype='<U1')

In [8]:
a=np.array(range(1,10))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# print array starts from 1 to 50 skip by 2
a=np.array(range(1,50,2))
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [10]:
# print array starts from 100 to 50 
a=np.array(range(100,50,-1))
a

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51])

In [11]:
a.ndim


1

In [12]:
b=np.array([[1,2,4],[5,3,6]])
b

array([[1, 2, 4],
       [5, 3, 6]])

In [13]:
b.ndim # no of dimesions

2

In [14]:
b.size # no of elements

6

In [15]:
b.shape

(2, 3)

In [16]:
c=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [17]:
c.ndim


3

In [18]:
c.size

12

In [19]:
c.shape


(2, 2, 3)

In [20]:
c.dtype

dtype('int32')

In [21]:
# 2-d array
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
d.ndim

2

In [23]:
d[0][0]

1

In [24]:
d[0,0]

1

In [25]:
## n-d array
s=np.array([3,5,6,7],ndmin=3)
s

array([[[3, 5, 6, 7]]])

In [26]:
i=np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
b=np.ones(5,dtype="int")
b

array([1, 1, 1, 1, 1])

In [29]:
b=np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
a=np.full(4,"hi")
a

array(['hi', 'hi', 'hi', 'hi'], dtype='<U2')

In [31]:
a=np.full((3,3),"hi")
a

array([['hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi']], dtype='<U2')

In [32]:
b.fill(4)
b

array([[4., 4.],
       [4., 4.],
       [4., 4.]])

In [33]:
b.fill(3)
b

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

In [34]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
## print array using arange method
# start range=20
# end range= 100
# skip by 2 numbers
a=np.arange(25,100,2)
a

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57,
       59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91,
       93, 95, 97, 99])

In [36]:
## print array using arange method
# start range=100
# end range= 1
a=np.arange(100,1,-1)
a

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2])

In [37]:
## Constructing  2d array from 1d array
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a.reshape(2,6) #parameters should be the multiples of number of elements

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [39]:
b=np.arange(100,20,-4)
b

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24])

In [40]:
b.size

20

In [41]:
b.reshape(10,2)

array([[100,  96],
       [ 92,  88],
       [ 84,  80],
       [ 76,  72],
       [ 68,  64],
       [ 60,  56],
       [ 52,  48],
       [ 44,  40],
       [ 36,  32],
       [ 28,  24]])

In [42]:
b.reshape(4,5)

array([[100,  96,  92,  88,  84],
       [ 80,  76,  72,  68,  64],
       [ 60,  56,  52,  48,  44],
       [ 40,  36,  32,  28,  24]])

In [43]:
b.reshape(5,4)

array([[100,  96,  92,  88],
       [ 84,  80,  76,  72],
       [ 68,  64,  60,  56],
       [ 52,  48,  44,  40],
       [ 36,  32,  28,  24]])

In [44]:
b.reshape(2,10)

array([[100,  96,  92,  88,  84,  80,  76,  72,  68,  64],
       [ 60,  56,  52,  48,  44,  40,  36,  32,  28,  24]])

In [45]:
c=np.arange(200)
c

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [46]:
c.reshape(4,50)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
         76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
     

In [47]:
c.reshape(10,20)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

In [48]:
c.reshape(20,10)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [49]:
c.reshape(8,25)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
        138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174],
      

In [50]:
c.reshape(25,8)

array([[  0,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31],
       [ 32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60,  61,  62,  63],
       [ 64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103],
       [104, 105, 106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140, 141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151],
       [152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 16

In [51]:
## random
a=np.random.randint(10)
a

3

In [52]:
## random
a=np.random.randint(10)
a

6

In [53]:
## random
a=np.random.randint(10,15)
a

14

In [54]:
## random
a=np.random.randint(15,20)
a

17

In [55]:
lw,uw=int(input()),int(input())
a=np.random.randint(lw,uw,8)
a.reshape(2,4)

34
54


array([[45, 37, 37, 49],
       [52, 43, 46, 43]])

In [56]:
b=np.random.random((3,4))
b

array([[0.45302067, 0.43824049, 0.2300498 , 0.07282257],
       [0.54848902, 0.06879349, 0.43684829, 0.51582294],
       [0.76965313, 0.89382661, 0.93222277, 0.24668455]])

In [57]:
b=np.random.randn(3,4)
b

array([[-1.38490463, -1.118555  , -1.11389353, -0.58361953],
       [ 0.02071003,  1.78900948, -0.41192959,  0.28128737],
       [ 1.46954913,  1.61799597, -1.01162028,  0.35423006]])

In [58]:
## linspace()
a=np.linspace(3,20)
a

array([ 3.        ,  3.34693878,  3.69387755,  4.04081633,  4.3877551 ,
        4.73469388,  5.08163265,  5.42857143,  5.7755102 ,  6.12244898,
        6.46938776,  6.81632653,  7.16326531,  7.51020408,  7.85714286,
        8.20408163,  8.55102041,  8.89795918,  9.24489796,  9.59183673,
        9.93877551, 10.28571429, 10.63265306, 10.97959184, 11.32653061,
       11.67346939, 12.02040816, 12.36734694, 12.71428571, 13.06122449,
       13.40816327, 13.75510204, 14.10204082, 14.44897959, 14.79591837,
       15.14285714, 15.48979592, 15.83673469, 16.18367347, 16.53061224,
       16.87755102, 17.2244898 , 17.57142857, 17.91836735, 18.26530612,
       18.6122449 , 18.95918367, 19.30612245, 19.65306122, 20.        ])

In [59]:
## linspace()
a=np.linspace(1,1)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
b=np.arange(20).reshape(4,5)
print(b)
print(b.transpose())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [61]:
a=np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [62]:
print(a[0,0:2])

[0 1]


In [63]:
print(a[1,1:3])

[6 7]


In [65]:
## Arithematic operations on arrays
#+,-,*,/

In [66]:
a,b=np.arange(5),np.arange(5)
print(a)
print(b)
c=a+b
print(c)

[0 1 2 3 4]
[0 1 2 3 4]
[0 2 4 6 8]


In [67]:
a,b=np.arange(4),np.arange(4)
print(a)
print(b)
c=a-b
print(c)

[0 1 2 3]
[0 1 2 3]
[0 0 0 0]


In [68]:
a,b=np.arange(4),np.arange(4)
print(a)
print(b)
c=a*b
print(c)

[0 1 2 3]
[0 1 2 3]
[0 1 4 9]


In [69]:
a,b=np.arange(5),np.arange(5)
print(a)
print(b)
c=a//b
print(c)

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 1 1 1]


<ipython-input-69-2bddc06dd3ea>:4: RuntimeWarning: divide by zero encountered in floor_divide
  c=a//b


In [70]:
## scientific calculations
np.log(1)

0.0

In [71]:
a=np.log([1,2,3,4])
a

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [72]:
a=np.sin([1,2,3,4])
a

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [76]:
# statistics
a=np.array([[1,23,78],[24,56,76]])
print(a)

[[ 1 23 78]
 [24 56 76]]


In [77]:
print(np.amin(a))
print(np.amax(a))


1
78


In [78]:
a=np.array([5,6,7])
print(np.mean(a))

6.0


In [79]:
print(np.median(a))

6.0


In [80]:
## standard deviation
## square root of average of square deviations of mean

In [81]:
print(np.std(a))

0.816496580927726


In [82]:
## variance
# average of squares of standard deviations

In [83]:
print(np.var(a))

0.6666666666666666


In [84]:
## Aggregation
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
min(a)


0

In [86]:
max(a)

19

In [87]:
np.min(a)

0

In [88]:
np.max(a)

19

In [89]:
a.sum()

190

In [90]:
M = np.random.random((3, 4))
print(M)

[[0.33628543 0.24963345 0.00816877 0.44138075]
 [0.41427397 0.35609906 0.80212896 0.58742321]
 [0.79226    0.09603565 0.41945684 0.77271621]]


In [91]:
M.sum()


5.275862306623781

In [92]:
M.min()

0.008168772293942195

In [93]:
M.max()

0.8021289592342379

In [94]:
## filtering
a=np.array([41,42,43,44,45])
f=a>42
n=a[f]
print(f)
print(a)




[False False  True  True  True]
[41 42 43 44 45]


In [95]:
b=np.array([24,31,34,56,21])
f=b%2==0
n=b[f]
print(n)

[24 34 56]


In [101]:
## saving with data
from numpy import asarray
from numpy import savetxt
data=np.array([[1,2,3,4],[5,6,7,8]])
savetxt('data.csv',data,delimiter=",")# a file is created


In [102]:
## displaying the data from .csv file
from numpy import loadtxt
data=loadtxt('data.csv',delimiter=",")#used to display the file created
data

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])